_prefs: 
  saveCenter: true
_properties: 
  bridge: 
    "group-by": layer
attribution: "<a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox &copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 112.7637
  - 12.2971
  - 5
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 18
minzoom: 0
name: OSM Bright 2
source: "tmsource:///Users/msemenik/dev/osm/osm2pgsql-osm-bright.tm2source"
styles: 
  - style.mss
  - road.mss
  - labels.mss
  - fonts.mss
template: ''
