_prefs: 
  baselayer: ''
  mapid: skorasaurus.5eb85050
  saveCenter: true
_properties: 
  bridge: 
    "group-by": layer
attribution: Map data © OpenStreetMap contributors
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -81.70276343822479
  - 41.501289723897955
  - 16
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 22
minzoom: 0
name: OSM Bright 2
source: "mapbox:///mapbox.mapbox-streets-v42-dev"
styles: 
  - style.mss
  - road.mss
  - labels.mss
template: ''
