#!/usr/bin/python

import os, inspect, re
from subprocess import check_output

mss = """// This style is automatically generated by scripts/update-css.py
// Don't edit it manually

Map { font-directory: url("fonts/"); }

"""

dir = os.path.abspath(os.path.dirname(os.path.dirname(inspect.getfile(inspect.currentframe())))) + '/'

def getFonts():
    res = {}
    output = check_output('/usr/local/bin/otfinfo -i ' +  dir + 'fonts/*.?tf', shell=True).splitlines()
    for line in output:
        if ':Full name:' not in line: continue
        file, dummy, name = line.split(':')
        file = file.split('/')[-1]
        name = name.strip()
        style = str(re.findall('-(.+?)\\..+?$', file)[0]).lower()
        if style == 'regular' and not name.endswith('Regular'): name += ' Regular' # I hate you Mapnik!
        if not style in res: res[style] = []
        res[style].append(name)
    return res

list = getFonts()
for style in list:
    if style != 'regular': list[style].extend(list['regular']) # fallbacks for bold and italic which support fewer scripts
    mss += '@' + style + ": '" + "', '".join(list[style]) + "';\n"

open(dir + 'fonts.mss', 'w').write(mss)
